import type { Company, JobPost, ScreeningQuestion } from './types';

const screeningStandard: ScreeningQuestion[] = [
  {
    id: 'sq1',
    questionText: 'Do you have the right to work in Singapore?',
    questionType: 'yes_no',
  },
  {
    id: 'sq2',
    questionText: 'Years of experience in a similar role?',
    questionType: 'text',
  },
];

export const mockCompanies: Company[] = [
  {
    companyId: 'co1',
    name: 'Deloitte Singapore',
    industry: 'Professional Services',
    size: '51–200',
    website: 'https://example.com',
    description: 'Regional audit and advisory firm.',
    location: 'Singapore',
    verificationStatus: 'approved',
  },
  {
    companyId: 'co2',
    name: 'PwC Singapore',
    industry: 'Technology',
    size: '201–500',
    description: 'Payments and compliance technology.',
    location: 'Singapore',
    verificationStatus: 'approved',
  },
  {
    companyId: 'co3',
    name: 'Singapore Airlines',
    industry: 'Aviation',
    size: '1–50',
    description: 'Growing retailer — verification pending.',
    location: 'Singapore',
    verificationStatus: 'pending',
  },
];

export const mockJobsSeed: JobPost[] = [
  {
    jobId: 'job1',
    companyId: 'co1',
    title: 'Senior Audit Manager',
    description:
      'Lead statutory audits for SME and listed clients. Coordinate with engagement managers and clients.',
    requirements: 'CA / CPA or equivalent. 3+ years audit experience. Strong communication skills.',
    benefits: 'Medical, flexible work, CPE support.',
    location: 'Singapore',
    salaryMin: 5500,
    salaryMax: 7500,
    salaryCurrency: 'SGD',
    employmentType: 'full_time',
    workArrangement: 'hybrid',
    seniority: 'Senior',
    industry: 'Finance & Accounting',
    skills: ['External Audit', 'IFRS', 'Statutory audit', 'Excel'],
    postedAt: new Date(Date.now() - 2 * 86400000).toISOString(),
    closingAt: new Date(Date.now() + 20 * 86400000).toISOString(),
    status: 'active',
    screeningQuestions: screeningStandard,
    viewsCount: 128,
    applicationsCount: 14,
    featured: true,
    officeDistrict: 'Raffles Place',
  },
  {
    jobId: 'job2',
    companyId: 'co2',
    title: 'Assurance Manager',
    description: 'Own roadmap for regulatory reporting products. Work with engineering and risk teams.',
    requirements: '5+ years PM experience in B2B SaaS or fintech. Stakeholder management.',
    benefits: 'ESOP, hybrid, learning budget.',
    location: 'Singapore',
    salaryMin: 8000,
    salaryMax: 11000,
    salaryCurrency: 'SGD',
    employmentType: 'full_time',
    workArrangement: 'hybrid',
    seniority: 'Mid',
    industry: 'Finance & Accounting',
    skills: ['Assurance', 'IFRS', 'Client management', 'Excel'],
    postedAt: new Date(Date.now() - 5 * 86400000).toISOString(),
    closingAt: new Date(Date.now() + 14 * 86400000).toISOString(),
    status: 'active',
    screeningQuestions: screeningStandard,
    viewsCount: 89,
    applicationsCount: 9,
    officeDistrict: 'Marina Bay',
  },
  {
    jobId: 'job3',
    companyId: 'co1',
    title: 'Tax Associate',
    description: 'Corporate tax compliance and advisory for local clients.',
    requirements: 'Degree in Accounting. Tax experience preferred.',
    location: 'Singapore',
    salaryMin: 4000,
    salaryMax: 5500,
    salaryCurrency: 'SGD',
    employmentType: 'full_time',
    workArrangement: 'on_site',
    seniority: 'Entry',
    industry: 'Professional Services',
    skills: ['Tax', 'Excel', 'Corporate tax'],
    postedAt: new Date(Date.now() - 1 * 86400000).toISOString(),
    closingAt: new Date(Date.now() + 10 * 86400000).toISOString(),
    status: 'pending_moderation',
    screeningQuestions: screeningStandard,
    viewsCount: 0,
    applicationsCount: 0,
  },
  {
    jobId: 'job4',
    companyId: 'co3',
    title: 'Finance Business Partner',
    description: 'Oversee daily retail operations and team scheduling.',
    requirements: '2+ years retail leadership.',
    location: 'Singapore',
    salaryMin: 3500,
    salaryMax: 4200,
    salaryCurrency: 'SGD',
    employmentType: 'full_time',
    workArrangement: 'on_site',
    seniority: 'Senior',
    industry: 'Finance & Accounting',
    skills: ['FP&A', 'Budgeting', 'Stakeholder management'],
    postedAt: new Date(Date.now() - 3 * 86400000).toISOString(),
    closingAt: new Date(Date.now() + 30 * 86400000).toISOString(),
    status: 'active',
    screeningQuestions: [{ id: 'sq1', questionText: 'Available to work weekends?', questionType: 'yes_no' }],
    viewsCount: 45,
    applicationsCount: 6,
    officeDistrict: 'Changi',
  },
];
